apiVersion: 1

groups:
  - name: service-status
    rules:
      - alert: ServiceDown
        expr: up{job=~"user-microservice|genai-microservice|journal-microservice|api-gateway"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "{{ $labels.job }} has been down for more than 1 minute."