apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: {{ .Values.namespaceId }}
spec:
  selector:
    app: zenai-api-gateway-selector
  ports:
    - port: {{ .Values.apiGateway.service.port }}
      targetPort: {{ .Values.apiGateway.service.targetPort }}
      protocol: TCP
  type: {{ .Values.apiGateway.service.type }}