apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenai-client
  namespace: {{ .Values.namespaceId }}
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: zenai-client-selector
  template:
    metadata:
      labels:
        app: zenai-client-selector
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          env:
          {{- range .Values.client.env }}
            - name: {{ .name }}
              {{- if .value }}
              value: "{{ .value }}"
              {{- end }}
              {{- if .valueFrom }}
              valueFrom:
{{ toYaml .valueFrom | indent 16 }}
              {{- end }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.client.service.targetPort }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
