apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: {{ .Values.namespaceId }}
spec:
  selector:
    app: zenai-client-selector
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
      protocol: TCP
  type: {{ .Values.client.service.type }}