apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenai-genai
  namespace: {{ .Values.namespaceId }}
spec:
  replicas: {{ .Values.genai.replicaCount }}
  selector:
    matchLabels:
      app: zenai-genai-selector
  template:
    metadata:
      labels:
        app: zenai-genai-selector
    spec:
      containers:
        - name: genai
          image: "{{ .Values.genai.image.repository }}:{{ .Values.genai.image.tag }}"
          imagePullPolicy: {{ .Values.genai.image.pullPolicy }}
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
          ports:
            - containerPort: {{ .Values.genai.service.targetPort }}
          env:
{{- with .Values.genai.env }}
{{ toYaml . | indent 12 }}
{{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
