apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: {{ .Values.namespaceId }}
spec:
  selector:
    app: zenai-genai-selector
  ports:
    - port: {{ .Values.genai.service.port }}
      targetPort: {{ .Values.genai.service.targetPort }}
      protocol: TCP
  type: {{ .Values.genai.service.type }}