apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: dashboards
data:
  user-microservice-dashboard.json: |-
    {{ .Files.Get "files/grafana/dashboards/user-microservice-dashboard.json" | nindent 4 }}
  journal-microservice-dashboard.json: |-
    {{ .Files.Get "files/grafana/dashboards/journal-microservice-dashboard.json" | nindent 4 }}
  genai-dashboard.json: |-
    {{ .Files.Get "files/grafana/dashboards/genai-dashboard.json" | nindent 4 }}
  api-gateway-dashboard.json: |-
    {{ .Files.Get "files/grafana/dashboards/api-gateway-dashboard.json" | nindent 4 }}
  dashboard-provider.yml: |-
    apiVersion: 1
    providers:
      - name: 'default'
        type: file
        options:
          path: /etc/grafana/provisioning/dashboards