{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zenai-ingress
  namespace: {{ .Values.namespaceId }}
{{- $annotations := .Values.ingress.annotations | default dict }}
{{- if $annotations }}
  annotations:
{{ toYaml $annotations | indent 4 }}
{{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - "{{ .Values.namespaceId }}.student.k8s.aet.cit.tum.de"
      secretName: "team-zenai-tls"
  {{- end }}
  rules:
    - host: "{{ .Values.namespaceId }}.student.k8s.aet.cit.tum.de"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: {{ .Values.client.service.port }}
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: {{ .Values.apiGateway.service.port }}
{{- end }}
