apiVersion: v1
kind: Service
metadata:
  name: journal-service
  namespace: {{ .Values.namespaceId }}
spec:
  selector:
    app: zenai-journal-selector
  ports:
    - port: {{ .Values.journal.service.port }}
      targetPort: {{ .Values.journal.service.targetPort }}
      protocol: TCP
  type: {{ .Values.journal.service.type }}