apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.namespaceId }}
spec:
  ports:
    - port: {{ .Values.prometheus.service.port }}
      targetPort: {{ .Values.prometheus.service.port }}
      protocol: TCP
      name: http
  selector:
    app: prometheus