apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alert-rules
  namespace: {{ .Values.namespaceId }}
  labels:
    app: prometheus
data:
  microservice.rules.yml: |
    groups:
      - name: microservice.rules
        rules:
          - alert: ApiGatewayDown
            expr: up{job="gateway-service"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "API Gateway is down"
              description: "No targets for job 'gateway-service' have been up for more than 1 minute."

          - alert: UserMicroserviceDown
            expr: up{job="user-service"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "User Microservice is down"
              description: "No targets for job 'user-service' have been up for more than 1 minute."

          - alert: JournalMicroserviceDown
            expr: up{job="journal-service"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Journal Microservice is down"
              description: "No targets for job 'journal-service' have been up for more than 1 minute."

          - alert: GenaiMicroserviceDown
            expr: up{job="genai-service"} == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "GenAI Microservice is down"
              description: "No targets for job 'genai-service' have been up for more than 1 minute."