global:
  scrape_interval: 15s

#TODO: Change targets if we are going to use it inside kubernetes
scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:8085']

  - job_name: 'user-microservice'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['user-microservice:8080']

  - job_name: 'journal-microservice'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['journal-microservice:8081']

  - job_name: 'genai-microservice'
    metrics_path: /metrics
    static_configs:
      - targets: ['genai-microservice:8082']