spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 30s
      discovery:
        locator:
          enabled: false
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          "[/**]":
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: false

server:
  port: 8085

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      user-service-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        sliding-window-size: 10
      journal-service-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        sliding-window-size: 10
      genai-service-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30000
        sliding-window-size: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway, prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    prometheus:
      enabled: true

logging:
  level:
    "[org.springframework.cloud.gateway]": DEBUG
    "[com.example.api_gateway]": DEBUG
    "[reactor.netty.http.client]": DEBUG
