name: GenAI Service Tests

on:
  push:
    branches: [ main, develop ]
    paths: [ 'genai/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'genai/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      working-directory: ./genai
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test_requirements.txt
    
    - name: Run Unit Tests
      working-directory: ./genai
      run: |
        python -m pytest tests/test_openwebui_llm.py tests/test_models.py tests/test_summary_chain.py -v --tb=short
    
    - name: Run API Integration Tests
      working-directory: ./genai
      run: |
        python -m pytest tests/test_api_endpoints.py -v --tb=short
    
    - name: Run Full Integration Tests
      working-directory: ./genai
      run: |
        python -m pytest tests/test_integration.py -v --tb=short
    
    - name: Generate Coverage Report
      working-directory: ./genai
      run: |
        python -m pytest tests/ --cov=app --cov-report=xml --cov-report=term-missing --cov-fail-under=80
    
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./genai/coverage.xml
        directory: ./genai
        flags: genai
        name: genai-coverage
        fail_ci_if_error: false
