---
- name: Install Docker and Docker Compose
  hosts: docker_server
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
          - rsync
        state: present

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker CE
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: true

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Install Docker Python modules
      ansible.builtin.apt:
        name:
          - python3-docker
          - python3-requests
        state: present

- name: Configure Docker user permissions
  hosts: docker_server
  become: true
  tasks:
    - name: Add ubuntu user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true

    - name: Reset connection to apply group changes
      ansible.builtin.meta: reset_connection

- name: Deploy application
  hosts: docker_server
  become: false
  vars:
    github_actor: "{{ github_actor | default('') }}"
    github_token: "{{ github_token | default('') }}"
  tasks:
    - name: Copy project files to remote server
      ansible.builtin.synchronize:
        src: ../
        dest: /home/ubuntu/app/
        delete: true
        recursive: true
        rsync_opts:
          - "--exclude=.git"
          - "--exclude=.github"
          - "--exclude=node_modules"
          - "--exclude=.venv"
          - "--exclude=__pycache__"
          - "--exclude=.terraform"
          - "--exclude=*.log"
          - "--exclude=.env*"
        owner: false
        group: false

    - name: Set proper ownership of app directory
      ansible.builtin.file:
        path: /home/ubuntu/app
        owner: ubuntu
        group: ubuntu
        recurse: true
      become: true

    - name: Log in to GitHub Container Registry
      community.docker.docker_login:
        registry_url: ghcr.io
        username: "{{ github_actor }}"
        password: "{{ github_token }}"
      when: github_actor != '' and github_token != ''
      register: docker_login_result
      failed_when: false  # Don't fail if login fails - we can still deploy with public images

    - name: Display login result
      ansible.builtin.debug:
        msg: >-
          GitHub Container Registry login
          {{ 'succeeded' if docker_login_result.failed is defined and not docker_login_result.failed else 'failed or skipped' }}
      when: github_actor != '' and github_token != ''

    - name: Stop existing containers
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/app
        files:
          - docker-compose.yml
        state: absent
      register: docker_stop_result
      failed_when: false  # Don't fail if no containers exist to stop

    - name: Display stop result
      ansible.builtin.debug:
        msg: >-
          Container stop
          {{ 'completed' if not docker_stop_result.failed else 'failed (containers may not have existed)' }}

    - name: Pull latest images
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/app
        files:
          - docker-compose.yml
        pull: "always"
        state: present
        recreate: "never"
      register: docker_pull_result

    - name: Start docker containers with compose
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/app
        files:
          - docker-compose.yml
        state: present
        recreate: "always"
        remove_orphans: true
      register: docker_compose_result

    - name: Wait for containers to be ready
      ansible.builtin.pause:
        seconds: 10

    - name: Check container status
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/app
        files:
          - docker-compose.yml
        state: present
      register: container_status

    - name: Display deployment information
      ansible.builtin.debug:
        msg:
          - "Deployment completed successfully!"
          - "Application URLs:"
          - "  - Client: http://{{ ansible_host }}:3000"
          - "  - API: http://{{ ansible_host }}:8085"
