global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus.zenai-team.svc.cluster.local:9090']

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['gateway-service.zenai-team.svc.cluster.local:8085']

  - job_name: 'user-microservice'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['user-service.zenai-team.svc.cluster.local:8080']

  - job_name: 'journal-microservice'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['journal-service.zenai-team.svc.cluster.local:8081']

  - job_name: 'genai-microservice'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['genai-service.zenai-team.svc.cluster.local:8082']