name: Validates Kubernetes' chart structure and templates

on:
  push:
    paths:
      - 'helm/**'
  pull_request:
    paths:
      - 'helm/**'

jobs:
  helm-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Lint Helm charts
        run: helm lint ./helm

      - name: Helm template render test
        run: helm template zenai-app ./helm --values ./helm/values.yaml