name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  client:
    name: Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

  server:
    name: Server
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, journal-microservice, user-microservice]
    defaults:
      run:
        working-directory: server/${{ matrix.service }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

  genai:
    name: Genai server
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: genai

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with Ruff
        run: |
          pip install ruff
          ruff check

      - name: Start FastAPI server in background
        run: |
          fastapi run --host 0.0.0.0 --port 8000 &
          # wait a few seconds for server to be ready
          sleep 5

      - name: Health check FastAPI server
        run: |
          curl --fail http://localhost:8000/api/health

  ansible-lint:
    uses: ./.github/workflows/ansible_lint.yml
