name: Deploy Kubernetes to AET cluster

on:
  push:
    branches:
#      - TODO: Change to main
      - feat/kubernets-config-and-helm-charts

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v4


      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0

      - name: Configure kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG" > $HOME/.kube/config

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install zenai-app ./helm \
          --namespace zenai-team \
          -f ./helm/values.yaml