name: Provision EC2 instance and Setup with Ansible

on:
  workflow_dispatch:
  push:
    paths:
      - "terraform/**"
      - "ansible/**"
      - ".github/workflows/infra.yml"
    branches:
      - main

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Apply Terraform
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform apply -auto-approve

      - name: Get EC2 Public IP
        id: ip
        working-directory: terraform
        run: |
          echo "ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT

      - name: Create Ansible inventory
        run: |
          echo "[docker_server]" > ansible/inventory.ini
          echo "${{ steps.ip.outputs.ip }}" >> ansible/inventory.ini

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Add SSH private key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/private_key.pem
          chmod 400 ~/.ssh/private_key.pem

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbook.yml -i ansible/inventory.ini \
          --private-key ~/.ssh/private_key.pem \
          -u ubuntu
