name: Provision EC2 instance and Setup with Ansible

on:
  workflow_dispatch:
  push:
    paths:
      - "terraform/**"
      - "ansible/**"
      - ".github/workflows/infra.yml"
    branches:
      - main

jobs:
  provision:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Initialize Terraform
        working-directory: terraform
        run: terraform init

      - name: Apply Terraform
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          terraform apply -auto-approve \
            -var="ami_id=${{ secrets.AMI_ID }}" \
            -var="key_name=${{ secrets.AWS_KEY_NAME }}"

      - name: Get EC2 Public IP
        id: ip
        working-directory: terraform
        run: |
          echo "ip=$(terraform output -raw ec2_public_ip)" >> $GITHUB_OUTPUT

      - name: Create Ansible inventory
        run: |
          echo "[ec2]" > ansible/inventory.ini
          echo "${{ steps.ip.outputs.ip }}" >> ansible/inventory.ini

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Run Ansible Playbook
        run: |
          ansible-playbook ansible/playbook.yml -i ansible/inventory.ini \
            --private-key "${{ secrets.SSH_PRIVATE_KEY_PATH }}" \
            -u ubuntu
